# Generated by Django 4.2.2 on 2023-07-19 07:23

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='otp',
            field=models.CharField(max_length=6, null=True, verbose_name='OTP'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='otp_expiry_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='OTP Expiry Time'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 19, 7, 23, 42, 183600, tzinfo=datetime.timezone.utc), editable=False, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 19, 7, 23, 42, 183600, tzinfo=datetime.timezone.utc), verbose_name='Joining Date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='email@mydomain.cm', max_length=254, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 19, 7, 23, 42, 183600, tzinfo=datetime.timezone.utc), editable=False, verbose_name='Updated On'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 19, 7, 23, 42, 185596, tzinfo=datetime.timezone.utc), editable=False, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile.png', null=True, upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 19, 7, 23, 42, 185596, tzinfo=datetime.timezone.utc), editable=False, verbose_name='Updated On'),
        ),
    ]
