# Generated by Django 4.2.2 on 2023-07-19 08:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('users', '0002_userprofile_otp_userprofile_otp_expiry_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 19, 8, 14, 27, 879979, tzinfo=datetime.timezone.utc), editable=False, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 19, 8, 14, 27, 879979, tzinfo=datetime.timezone.utc), verbose_name='Joining Date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 19, 8, 14, 27, 879979, tzinfo=datetime.timezone.utc), editable=False, verbose_name='Updated On'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.city', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 19, 8, 14, 27, 882970, tzinfo=datetime.timezone.utc), editable=False, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, default='first name', max_length=100, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='prefix',
            field=models.CharField(blank=True, default='prefix', max_length=10, null=True, verbose_name='Prefix'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.region', verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 19, 8, 14, 27, 882970, tzinfo=datetime.timezone.utc), editable=False, verbose_name='Updated On'),
        ),
    ]
