# Generated by Django 4.2.2 on 2023-07-21 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_created_on_alter_user_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notifications',
            field=models.BooleanField(default=True, verbose_name='Notifications'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 21, 9, 59, 59, 677670, tzinfo=datetime.timezone.utc), editable=False, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 21, 9, 59, 59, 677670, tzinfo=datetime.timezone.utc), verbose_name='Joining Date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 21, 9, 59, 59, 677670, tzinfo=datetime.timezone.utc), editable=False, verbose_name='Updated On'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 21, 9, 59, 59, 679665, tzinfo=datetime.timezone.utc), editable=False, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 21, 9, 59, 59, 679665, tzinfo=datetime.timezone.utc), editable=False, verbose_name='Updated On'),
        ),
    ]
