# Generated by Django 4.2.3 on 2023-07-25 10:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_user_created_on_alter_user_date_joined_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 7, 25, 10, 19, 5, 180333, tzinfo=datetime.timezone.utc
                ),
                editable=False,
                verbose_name="Created On",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 7, 25, 10, 19, 5, 180058, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Joining Date",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_on",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 7, 25, 10, 19, 5, 180388, tzinfo=datetime.timezone.utc
                ),
                editable=False,
                verbose_name="Updated On",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 7, 25, 10, 19, 5, 183623, tzinfo=datetime.timezone.utc
                ),
                editable=False,
                verbose_name="Created On",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="updated_on",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 7, 25, 10, 19, 5, 183676, tzinfo=datetime.timezone.utc
                ),
                editable=False,
                verbose_name="Updated On",
            ),
        ),
    ]
