# Generated by Django 4.2.3 on 2023-07-25 10:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_user_created_on_alter_user_date_joined_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 7, 25, 10, 58, 32, 696637, tzinfo=datetime.timezone.utc
                ),
                editable=False,
                verbose_name="Created On",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 7, 25, 10, 58, 32, 696376, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Joining Date",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="Is Active?"),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_on",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 7, 25, 10, 58, 32, 696714, tzinfo=datetime.timezone.utc
                ),
                editable=False,
                verbose_name="Updated On",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 7, 25, 10, 58, 32, 701555, tzinfo=datetime.timezone.utc
                ),
                editable=False,
                verbose_name="Created On",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="updated_on",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 7, 25, 10, 58, 32, 701625, tzinfo=datetime.timezone.utc
                ),
                editable=False,
                verbose_name="Updated On",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
