# Generated by Django 4.2.3 on 2023-07-26 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_user_created_on_alter_user_date_joined_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 7, 26, 16, 35, 3, 977999, tzinfo=datetime.timezone.utc
                ),
                editable=False,
                verbose_name="Created On",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 7, 26, 16, 35, 3, 977731, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Joining Date",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_on",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 7, 26, 16, 35, 3, 978066, tzinfo=datetime.timezone.utc
                ),
                editable=False,
                verbose_name="Updated On",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 7, 26, 16, 35, 3, 988305, tzinfo=datetime.timezone.utc
                ),
                editable=False,
                verbose_name="Created On",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="updated_on",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 7, 26, 16, 35, 3, 988386, tzinfo=datetime.timezone.utc
                ),
                editable=False,
                verbose_name="Updated On",
            ),
        ),
    ]
