# Generated by Django 4.2.3 on 2023-08-02 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_alter_user_created_on_alter_user_date_joined_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created On"),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Joining Date"),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_on",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Updated On"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created On"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="updated_on",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Updated On"),
        ),
        migrations.CreateModel(
            name="MediaFiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_file",
                    models.FileField(
                        blank=True, default="profile.png", null=True, upload_to="media"
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=50, null=True, verbose_name="Title"),
                ),
                (
                    "file_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Profile Pictures", "Profile Pictures"),
                            ("User Documents", "User Documents"),
                            ("Company Documents", "Company Documents"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="File Type",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Is Active?"),
                ),
                (
                    "updated_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="Updated On"),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_media_files",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
        ),
    ]
