# Generated by Django 4.2.3 on 2023-08-07 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
