# Generated by Django 4.2.3 on 2023-08-31 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0017_delete_userchartdata"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrafficData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("count", models.IntegerField()),
                ("device_type", models.CharField(max_length=50)),
            ],
        ),
    ]
