# Generated by Django 4.2.3 on 2023-09-04 10:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0020_product"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Product",
        ),
    ]
