# Generated by Django 4.2.4 on 2023-08-25 10:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("admin_volt", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserChartData",
        ),
    ]
