# Generated by Django 4.2.2 on 2023-06-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppStoreLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('apple_store_link', models.URLField(blank=True, null=True, verbose_name='Apple Store Link')),
                ('google_play_store_link', models.URLField(blank=True, null=True, verbose_name='Google Play Store Link')),
                ('apple_store_logo', models.ImageField(blank=True, null=True, upload_to='home/app_stores', verbose_name='Apple Store Logo')),
                ('google_play_store_logo', models.ImageField(blank=True, null=True, upload_to='home/app_stores', verbose_name='Google Play Store Logo')),
            ],
            options={
                'verbose_name': 'App Stores Link',
                'verbose_name_plural': 'App Stores Link',
            },
        ),
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Privacy Policy',
                'verbose_name_plural': 'Privacy Policy',
            },
        ),
        migrations.CreateModel(
            name='TermsAndCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Terms & Conditions',
                'verbose_name_plural': 'Terms & Conditions',
            },
        ),
    ]
