# Generated by Django 4.2.2 on 2023-06-21 12:06

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['title'], unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('plan_period_type', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('custom', 'Custom')], max_length=10, verbose_name='Plan Period Type')),
                ('apple_product_id', models.CharField(max_length=32, null=True, verbose_name='Apple Product ID')),
                ('description', models.TextField(blank=True, help_text='A description of the subscription plan')),
                ('grace_period', models.PositiveIntegerField(default=0, help_text='How many days after the subscription ends before the subscription expires.', verbose_name='Grace Period')),
                ('upgrade_from_plans', models.ManyToManyField(blank=True, to='subscriptions.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Title')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('plan_period_type', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('custom', 'Custom')], max_length=10, verbose_name='Plan Period Type')),
                ('is_cancelled', models.BooleanField(default=False, help_text='whether this subscription is cancelled or not', verbose_name='Cancelled')),
                ('payment_type', models.CharField(blank=True, choices=[('apple_iap', 'apple_iap'), ('stripe_card', 'Stripe Card')], default=None, max_length=20, null=True, verbose_name='Payment Type')),
                ('is_trial_period', models.BooleanField(default=False, verbose_name='Trial Period')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started at')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Ended at')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Cancelled at')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('upgrade_charge_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Upgrade Charge Amount')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='subscriptions.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'ordering': ('-created',),
            },
        ),
    ]
