# Generated by Django 4.2.3 on 2023-08-16 07:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetClasses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "assetclass_id",
                    models.CharField(
                        default="",
                        editable=False,
                        max_length=125,
                        unique=True,
                        verbose_name="Id",
                    ),
                ),
                (
                    "assetclass_name",
                    models.CharField(
                        default="asset class", max_length=150, verbose_name="Name"
                    ),
                ),
                (
                    "percent_markup",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.0,
                        editable=False,
                        max_digits=10,
                        verbose_name="Percent Markup",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active?"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_user_assetclass",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_user_assetclass",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Priority Gold Asset Class",
                "verbose_name_plural": "Priority Gold Asset Classes",
                "ordering": ("-updated",),
            },
        ),
        migrations.CreateModel(
            name="Grades",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "grade_name",
                    models.CharField(
                        default="grade", max_length=150, verbose_name="Name"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active?"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_user_grade",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_user_grade",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Priority Gold Metal Grade",
                "verbose_name_plural": "Priority Gold Metal Grades",
                "ordering": ("-updated",),
            },
        ),
        migrations.CreateModel(
            name="Metals",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "metal_id",
                    models.CharField(
                        default="",
                        editable=False,
                        max_length=125,
                        unique=True,
                        verbose_name="Id",
                    ),
                ),
                (
                    "metal_name",
                    models.CharField(
                        default="metal", max_length=150, verbose_name="Name"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active?"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_user_metal",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_user_metal",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Priority Gold Metal",
                "verbose_name_plural": "Priority Gold Metals",
                "ordering": ("-updated",),
            },
        ),
        migrations.CreateModel(
            name="ProductFamilies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "productfamily_id",
                    models.CharField(
                        default="",
                        editable=False,
                        max_length=125,
                        unique=True,
                        verbose_name="Id",
                    ),
                ),
                (
                    "productfamily_name",
                    models.CharField(
                        default="product family", max_length=250, verbose_name="Name"
                    ),
                ),
                (
                    "parent_id",
                    models.CharField(
                        blank=True,
                        default="",
                        editable=False,
                        max_length=125,
                        null=True,
                        verbose_name="Parent Id",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active?"),
                ),
                (
                    "assetclass",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="productfamily_assetclass",
                        to="portfolio.assetclasses",
                        to_field="assetclass_id",
                        verbose_name="Asset Class",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_user_product_family",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_user_product_family",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Priority Gold Product Family",
                "verbose_name_plural": "Priority Gold Product Families",
                "ordering": ("-updated",),
            },
        ),
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "sku",
                    models.CharField(
                        default="-", editable=False, max_length=20, verbose_name="SKU"
                    ),
                ),
                (
                    "product_name",
                    models.CharField(
                        default="product name", max_length=250, verbose_name="Name"
                    ),
                ),
                (
                    "product_description",
                    models.CharField(
                        default="description",
                        max_length=500,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "product_notes",
                    models.CharField(
                        default="note", max_length=500, null=True, verbose_name="Notes"
                    ),
                ),
                (
                    "ounces",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.0,
                        editable=False,
                        max_digits=10,
                        verbose_name="Ounces",
                    ),
                ),
                (
                    "commission",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.0,
                        editable=False,
                        max_digits=10,
                        verbose_name="Commission",
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True,
                        default="#",
                        max_length=500,
                        null=True,
                        verbose_name="Url",
                    ),
                ),
                (
                    "thumbnail_url",
                    models.CharField(
                        blank=True,
                        default="#",
                        max_length=500,
                        null=True,
                        verbose_name="Thumbnail Url",
                    ),
                ),
                (
                    "image_url",
                    models.CharField(
                        blank=True,
                        default="#",
                        max_length=500,
                        null=True,
                        verbose_name="Image Url",
                    ),
                ),
                (
                    "base_currency",
                    models.CharField(
                        blank=True,
                        default="USD",
                        max_length=15,
                        null=True,
                        verbose_name="Base Currency",
                    ),
                ),
                (
                    "base_ask",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.0,
                        editable=False,
                        max_digits=10,
                        verbose_name="Base Ask",
                    ),
                ),
                (
                    "base_bid",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.0,
                        editable=False,
                        max_digits=10,
                        verbose_name="Base Bid",
                    ),
                ),
                (
                    "cost_source",
                    models.CharField(
                        blank=True,
                        default="-",
                        max_length=20,
                        null=True,
                        verbose_name="Cost Source",
                    ),
                ),
                (
                    "bid_source",
                    models.CharField(
                        blank=True,
                        default="-",
                        max_length=20,
                        null=True,
                        verbose_name="Bid Source",
                    ),
                ),
                (
                    "cogs_percent",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.0,
                        editable=False,
                        max_digits=10,
                        verbose_name="Cogs Percent",
                    ),
                ),
                (
                    "cogs_dollar",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.0,
                        editable=False,
                        max_digits=10,
                        verbose_name="Cogs Dollar",
                    ),
                ),
                (
                    "grading_fee",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.0,
                        editable=False,
                        max_digits=10,
                        verbose_name="Grading Fee",
                    ),
                ),
                (
                    "fixed_markup_ask",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.0,
                        editable=False,
                        max_digits=10,
                        verbose_name="Fixed Markup Ask",
                    ),
                ),
                (
                    "percent_markup_ask",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.0,
                        editable=False,
                        max_digits=10,
                        verbose_name="Percent Markup Ask",
                    ),
                ),
                (
                    "fixed_markup_bid",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.0,
                        editable=False,
                        max_digits=10,
                        verbose_name="Fixed Markup Bid",
                    ),
                ),
                (
                    "percent_markup_bid",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.0,
                        editable=False,
                        max_digits=10,
                        verbose_name="Percent Markup Bid",
                    ),
                ),
                (
                    "fixed_markup_ask_wholesale",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.0,
                        editable=False,
                        max_digits=10,
                        verbose_name="Fixed Markup Ask Wholesale",
                    ),
                ),
                (
                    "percent_markup_ask_wholesale",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.0,
                        editable=False,
                        max_digits=10,
                        verbose_name="Percent Markup Ask Wholesale",
                    ),
                ),
                (
                    "fixed_markup_bid_wholesale",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.0,
                        editable=False,
                        max_digits=10,
                        verbose_name="Fixed Markup Bid Wholesale",
                    ),
                ),
                (
                    "percent_markup_bid_wholesale",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.0,
                        editable=False,
                        max_digits=10,
                        verbose_name="Percent Markup Bid Wholesale",
                    ),
                ),
                (
                    "wholesale_notes",
                    models.CharField(
                        default="note",
                        max_length=500,
                        null=True,
                        verbose_name="Wholesale Notes",
                    ),
                ),
                (
                    "track_inventory",
                    models.BooleanField(null=True, verbose_name="Track Inventory"),
                ),
                (
                    "retail_shipping",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.0,
                        editable=False,
                        max_digits=10,
                        verbose_name="Retail Shipping",
                    ),
                ),
                (
                    "retail_shipping_notes",
                    models.CharField(
                        default="note",
                        max_length=500,
                        null=True,
                        verbose_name="Retail Shipping Notes",
                    ),
                ),
                (
                    "wholesale_shipping",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.0,
                        editable=False,
                        max_digits=10,
                        verbose_name="Wholesale Shipping",
                    ),
                ),
                (
                    "wholesale_shipping_notes",
                    models.CharField(
                        default="note",
                        max_length=500,
                        null=True,
                        verbose_name="Wholesale Shipping Notes",
                    ),
                ),
                (
                    "product_status",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "1-2 Week Delay"),
                            (2, "2-3 Week Delay"),
                            (3, "3-4 Week Delay"),
                            (4, "4-5 Week Delay"),
                            (5, "5-6 Week Delay"),
                            (0, "In Stock"),
                            (9, "Out Of Stock"),
                            (10, "Unavailable"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "shipping_status",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "1-2 Week Delay"),
                            (2, "2-3 Week Delay"),
                            (3, "3-4 Week Delay"),
                            (4, "4-5 Week Delay"),
                            (5, "5-6 Week Delay"),
                            (6, "6-7 Week Delay"),
                            (7, "7-8 Week Delay"),
                            (8, "8-9 Week Delay"),
                            (9, "Out Of Stock"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active?"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_user_product",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "grade",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_grade",
                        to="portfolio.grades",
                        verbose_name="Grade",
                    ),
                ),
                (
                    "metal",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_metal",
                        to="portfolio.metals",
                        to_field="metal_id",
                        verbose_name="Metal",
                    ),
                ),
                (
                    "product_family",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_productfamily",
                        to="portfolio.productfamilies",
                        to_field="productfamily_id",
                        verbose_name="Product Family",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_user_product",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Priority Gold Product",
                "verbose_name_plural": "Priority Gold Products",
                "ordering": ("-updated",),
            },
        ),
        migrations.CreateModel(
            name="ProductPrices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "sku",
                    models.CharField(
                        default="-", editable=False, max_length=20, verbose_name="SKU"
                    ),
                ),
                (
                    "product_name",
                    models.CharField(
                        default="product name", max_length=250, verbose_name="Name"
                    ),
                ),
                (
                    "metal_name",
                    models.CharField(
                        default="metal", max_length=150, verbose_name="Metal"
                    ),
                ),
                (
                    "productfamily_name",
                    models.CharField(
                        default="product family",
                        max_length=250,
                        verbose_name="Product Family",
                    ),
                ),
                (
                    "assetclass_name",
                    models.CharField(
                        default="asset class",
                        max_length=150,
                        verbose_name="Asset Class",
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        default="-", editable=False, max_length=25, verbose_name="Grade"
                    ),
                ),
                (
                    "ounces",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.0,
                        editable=False,
                        max_digits=10,
                        verbose_name="Ounces",
                    ),
                ),
                (
                    "cogs",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.0,
                        editable=False,
                        max_digits=10,
                        verbose_name="Cogs",
                    ),
                ),
                (
                    "bid",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.0,
                        editable=False,
                        max_digits=10,
                        verbose_name="Bid",
                    ),
                ),
                (
                    "ask",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.0,
                        editable=False,
                        max_digits=10,
                        verbose_name="Ask",
                    ),
                ),
                (
                    "base_ask",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.0,
                        editable=False,
                        max_digits=10,
                        verbose_name="Base Ask",
                    ),
                ),
                (
                    "cost_source",
                    models.CharField(
                        blank=True,
                        default="-",
                        max_length=20,
                        null=True,
                        verbose_name="Cost Source",
                    ),
                ),
                (
                    "base_currency",
                    models.CharField(
                        blank=True,
                        default="USD",
                        max_length=15,
                        null=True,
                        verbose_name="Base Currency",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        default="description",
                        max_length=500,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "retail_shipping",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.0,
                        editable=False,
                        max_digits=10,
                        verbose_name="Retail Shipping",
                    ),
                ),
                (
                    "wholesale_shipping",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.0,
                        editable=False,
                        max_digits=10,
                        verbose_name="Wholesale Shipping",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active?"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_user_productprice",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_user_productprice",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Priority Gold Product Price",
                "verbose_name_plural": "Priority Gold Product Prices",
                "ordering": ("-updated",),
            },
        ),
        migrations.CreateModel(
            name="Portfolios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "sku",
                    models.CharField(
                        default="-", editable=False, max_length=20, verbose_name="SKU"
                    ),
                ),
                (
                    "ounces",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Ounces",
                    ),
                ),
                (
                    "metal_quantity",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Quantity",
                    ),
                ),
                (
                    "acquisition_cost",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Acquisition Cost",
                    ),
                ),
                (
                    "metal_value",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.0,
                        editable=False,
                        max_digits=10,
                        verbose_name="Metal Value",
                    ),
                ),
                (
                    "purchase_date",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023, 8, 16, 7, 19, 58, 129205, tzinfo=datetime.timezone.utc
                        ),
                        verbose_name="Purchase Date",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted?"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_by_portfolio",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "grade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="portfolio_product_grade",
                        to="portfolio.grades",
                        verbose_name="Grade",
                    ),
                ),
                (
                    "metal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="portfolio_metal",
                        to="portfolio.metals",
                        to_field="metal_id",
                        verbose_name="Metal",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="portfolio_product",
                        to="portfolio.products",
                        verbose_name="Product",
                    ),
                ),
                (
                    "product_family",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="portfolio_productfamily",
                        to="portfolio.productfamilies",
                        to_field="productfamily_id",
                        verbose_name="Product Family",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_by_portfolio",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Metal Portfolio",
                "verbose_name_plural": "User Metal Portfolios",
                "ordering": ("-updated",),
            },
        ),
    ]
