# Generated by Django 4.2.3 on 2023-09-05 05:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "portfolio",
            "0002_products_factor_rate_alter_portfolios_metal_quantity_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolios",
            name="purchase_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 9, 5, 5, 57, 21, 885530, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Purchase Date",
            ),
        ),
    ]
