# Generated by Django 4.2.3 on 2023-09-05 06:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0004_alter_portfolios_purchase_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolios",
            name="purchase_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Purchase Date"
            ),
        ),
    ]
